### ISSUE TITLE
help me!

### ISSUE THREAD

**Issue by GitHub-TXZ** [VendenIX/BrainMetaSegmentatorUI-Front#1]
Unable to query for studies at this time. Check your data source configuration or network connection

**Comment by VendenIX** [comment]
i, it appears that you have a CORS policy problem if you see that message in the Viewer. Have you launched the DICOM web server Orthanc on localhost:8042 from the Docker stack?

**Comment by VendenIX** [comment]
Hi, it appears that you have a CORS policy problem if you see that message in the Viewer. Have you launched the DICOM web server Orthanc on localhost:8042 from the Docker stack from the repository BrainSegmentatorUI-Back ?

**Comment by VendenIX** [comment]
Otherwise, you might need to edit the configuration file in the front end at `Viewers-3.7.0/platform/app/public/config/default.js` and change the following lines:

```javascript
wadoUriRoot: 'http://localhost:8080/wado',
qidoRoot: 'http://localhost:8080/dicom-web',
wadoRoot: 'http://localhost:8080/dicom-web',
```

However, in theory, if you launched the Docker stack, Nginx should handle this for you, and no further action should be necessary. Additionally, it might be a security setting in your browser causing this issue.

**Comment by GitHub-TXZ** [comment]
> Hi, it appears that you have a CORS policy problem if you see that message in the Viewer. Have you launched the DICOM web server Orthanc on localhost:8042 from the Docker stack from the repository BrainSegmentatorUI-Back ?

![image](https://github.com/user-attachments/assets/ec94aa58-e83c-45e8-a5a5-6ecc9722102c)
The localhost:8042 does't work.

**Comment by VendenIX** [comment]
Hmm strange, you don't see the orthanc interface on localhost:8042 or localhost:8080 or localhost/orthanc ?

**Comment by GitHub-TXZ** [comment]
> ```js
> ```js
> 
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> However, in theory, if you launched the Docker stack, Nginx should handle this for you, and no further action should be necessary. Additionally, it might be a security setting in your browser causing this issue.
> ```

Yes， pages not found.

**Comment by GitHub-TXZ** [comment]
Yes, pages not found

**Comment by GitHub-TXZ** [comment]
May I ask for any of your social media accounts for further communication? thank. Alternatively, if you could remotely control my computer using software such as sunlogin, to help me troubleshoot the issue, I would greatly appreciate it.

**Comment by GitHub-TXZ** [comment]
And localhost 5000 does't work.
![image](https://github.com/user-attachments/assets/219bac8c-d6ee-4b52-a9bc-b79cddc37ee5)
![image](https://github.com/user-attachments/assets/6a015185-bf99-45ab-bc21-8dd0f7f29861)

**Comment by VendenIX** [comment]
If you want, we can communicate on discord : Venden#4100

**Comment by GitHub-TXZ** [comment]
> If you want, we can communicate on discord : Venden#4100

Can you add my WeChat account 15674988722 ？      I would like to pay for you.

**Comment by VendenIX** [comment]
Discord vocal with screen share or nothing, sorry.
